Scenes/Customs/proceduralTexture.js

Hi,
I tried the sample and it seems camera.attachControl() was missing.

add camera.attachControl();

---

index.html

Shadows tutorial can be accessed from the front page again

Dead link removed

---

index.html

The "TRY" button link broke after the PG update.

Broken PG link

---

Demos/StandardRenderingPipeline/standardRenderingPipeline.js

@deltakosh just don't know if I should update the babylon.max.js and babylon.js references or if you do yourself

Updating standard rendering pipeline demo with luminance adaptation

---

_redirects

Revert "Deployment"

---

Demos/Normals/index.js

A corresponding change will need to happen in the engine.

Change tangents to match new tangent-space

---

index.html

I add new URL link to Perplexus Shadow Open BabylonJS WebGL game.

New URL to Perplexus Shadow Open Demo

---

Demos/Mansion/demo.js
Demos/Mansion/index.html

https://github.com/BabylonJS/Babylon.js/issues/3119

Add VRExperienceHelper to mansion demo

---

Demos/Mansion/demo.js
Demos/Mansion/index.html

Revert "Add VRExperienceHelper to mansion demo"

---

Demos/Normals/index.js

This must go together with https://github.com/BabylonJS/Babylon.js/pull/3452

Update normals demo

---

Demos/GLTFTests/generatedAssets.json
Demos/GLTFTests/index.js

This should get the new set of models ready for the validation suite.

Updated glTF Tests for validation

---

versionBuilder/index.html

in reference of this issue #288 
I think my way to make css for these buttons is a little... crappy, but I doesn't know anything about scss and how to manage it, so if anyone is volunteer?
At least, it works even on Internet Explorer ;)

adding two buttons for tools

---

versionBuilder/index.html

enhanced buttons

---

versionBuilder/index.html

text too long

---

Demos/GlowingEspilit/index.html
humans.txt

And "Matthieu Bué" correction :)

Website : Issue #4495 on Babylon.js repo.

---

index.html
js/main.js
scss/main.css

Centered download button on the landing page. Added hover-description to big WebGL on landing page so someone not familiar with WebGL can be provided a description. Added box-shadows to red button, green button, and blue button for appearance.

Fixed and Added some functionality to landing page

---

build/community/index.html
build/games/index.html
build/index.html
build/learn/index.html
build/specifications/index.html
build/tools/index.html
src/content/site.json

\+ guld building which have modify some files

suggestion with PR: adding "exporters" into main "tools" menu

---

src/content/community/config.json

Morterra Demo

---

README.md
build/Demos/Distraction/index.html
build/Demos/Retail/index2.html
build/Demos/Ruins/index.html
build/Demos/SSAO2/index.html
build/Demos/Spaceship/index.html
build/Demos/Sponza/index.html
build/Demos/SponzaDynamicShadows/index.html
build/Demos/UTD/index.html
build/Scenes/Sandbox/index.html
build/Scenes/WorldMonger/index.html
build/community/index.html
build/games/index.html
build/index.html
build/learn/index.html
build/playground/index.html
build/specifications/index.html
build/tools/index.html
src/templates/index-template.html

Some demos are pointing to http files when loaded over https. 
As some index.html files are not auto-generated (like the demos) the build directory had to be updated as well.

solving mixed-content (http/s) issues

---

src/content/community/config.json

removed "editor" to avoid title line break

---

build/community/index.html
build/ecommerce/index.html
build/games/index.html
build/index.html
build/learn/index.html
build/native/index.html
build/reactnative/index.html
build/specifications/index.html
build/tools/index.html
src/content/site.json
src/templates/index-template.html

Added car examples at the bottom

Update on e-commerce Page

---

build/Demos/ProductPage/device.js
build/Demos/ProductPage/index.html
build/Demos/ProductPage/styles.css

Adding HTML spinner and reworking style sheets to leverage mobile. ToDo: update camera position and animations when determining that device is mobile

Upates for mobile

---

build/Demos/WebGPU/forestWebGL.html
build/Demos/WebGPU/forestWebGPU.html

Makes animations loop continuously. Also, makes the UI responsive to different screen sizes. Applies to both WebGL and WebGPU versions.
Requested by @PirateJC

Forest demo: animations loop + ui responsive

---

build/Demos/WebGPU/forestWebGPU.html

Makes the webGPU animation loop

Forest demo: Make webGPU animation loop

---

build/Demos/WebGPU/forestWebGL.html
build/Demos/WebGPU/forestWebGPU.html

Updates the design of the forest demo to make it more video-friendly:

Update forest demo CSS

---

build/Demos/WebGPU/forestWebGPU.html
build/Demos/WebGPU/video/forestWebGL.html
build/Demos/WebGPU/video/forestWebGPU.html

At @sebavan's suggestion, restores the old versions of the forest demo and creates new versions under /webgpu/video/forestWebGL and /webgpu/video/forestWebGPU for the video versions.

Restore old forest demo and create video version

---

src/content/config.json

Corrected link on main page to ACE documentation

---

src/content/partners/config.json

- Removed link from Microsoft logo
- Updated page title

Minor fixes

---

src/content/config.json

Rearranging the elements in the carousel

Move book promo to first carousel slot

---

src/content/partners/config.json

Mercedes has removed their game, so dropping the link to it.

Remove dead link

---

src/templates/galleryBlock-template.html
src/templates/imagesBlock-template.html
src/templates/partnerLogo-template.html

Adding target="_blank" to templates that contain external links so users aren't exiting the web site when clicking on an external link.

Adding link targets to templates using external links

---

src/content/config.json

Update carousel link

---

src/content/community/config.json

updated link in community page

updated community page

---

build/featureDemos/index.html
src/content/featureDemos/config.json

Update to fix Bell demos PG

---

src/content/specifications/config.json

New features and doc links added to specifications page.

Adding new features to Specifications page

---

src/content/featureDemos/config.json

Demo needs to be fixed before relinking

Remove Music Visualizer

---

src/content/community/config.json

This link has probably not been updated by the owner and now leads to a phishing site

Remove broken link Demo

---

src/content/specifications/config.json

Discussion from https://forum.babylonjs.com/t/unlimited-lights-in-verson-7/50741

Quick change to light types to avoid confusion

---

src/content/specifications/config.json

Adding in HDR and EXR support to the specifications page

Update specifications for High Dynamic Range formats

---

build/community/index.html
build/creation/index.html
build/digitalTwinIot/index.html
build/ecommerce/index.html
build/featureDemos/index.html
build/games/index.html
build/index.html
build/industries/index.html
build/learn/index.html
build/metaverse/index.html
build/native/index.html
build/partners/index.html
build/pressRelease/index.html
build/reactnative/index.html
build/specifications/index.html
build/testimonials/index.html
build/tools/index.html
build/viewer.html
build/viewer/index.html
src/templates/index-template.html

Update Viewer to the latest (includes progress bar, spz support, and other new features).
I believe build/viewer/index.html had a mix of line endings, which makes it look like a lot of changes in the diff.

Update Viewer to latest

---

build/assets/styles/code.css
build/viewer.html
src/assets/styles/code.css

1. Fix scaling issue on mobile for the demo page.
| Before | After | 
|----------|----------|
| ![image](https://github.com/user-attachments/assets/48a79989-7e7a-4c4f-9092-2282a0eff9e3) | ![image](https://github.com/user-attachments/assets/4f13f087-fc88-42b4-8c43-f1022d19b9cb) |
2. Improve sizing of code snippet on mobile.
| Before | After | 
|----------|----------|
| ![image](https://github.com/user-attachments/assets/9824754f-2d49-4e7a-bbb0-50435964a3fb) | ![image](https://github.com/user-attachments/assets/2f4598db-b633-42be-854e-68e6b6d16439) |

More viewer related fixes

---

build/assets/styles/mediaQueries.css
build/assets/styles/viewerAndTextBlock.css
build/community/index.html
build/creation/index.html
build/digitalTwinIot/index.html
build/ecommerce/index.html
build/featureDemos/index.html
build/games/index.html
build/index.html
build/industries/index.html
build/learn/index.html
build/metaverse/index.html
build/native/index.html
build/partners/index.html
build/pressRelease/index.html
build/reactnative/index.html
build/specifications/index.html
build/testimonials/index.html
build/tools/index.html
build/viewer.html
build/viewer/index.html
src/assets/styles/mediaQueries.css
src/assets/styles/viewerAndTextBlock.css
src/content/viewer/config.json
src/templates/index-template.html
src/templates/viewerAndTextBlock-template.html

This change updates the Viewer page on the website with:
- Links to the docs
- Some top level info about features.
- Three live feature demos.
https://github.com/user-attachments/assets/e2648555-3464-4467-b670-d837a6b78ef2

Viewer doc links and features

---

build/assets/js/scripts.js
build/community/index.html
build/creation/index.html
build/digitalTwinIot/index.html
build/ecommerce/index.html
build/featureDemos/index.html
build/games/index.html
build/index.html
build/industries/index.html
build/learn/index.html
build/metaverse/index.html
build/native/index.html
build/partners/index.html
build/pressRelease/index.html
build/reactnative/index.html
build/specifications/index.html
build/testimonials/index.html
build/tools/index.html
build/viewer.html
build/viewer/index.html
src/assets/js/scripts.js
src/content/viewer/config.json
src/templates/index-template.html

- Add link to viewer configurator
- Update viewer to latest version
- Remove some of the explicit references to an environment file and let it use the embedded one

Add link to viewer configurator

---

build/assets/js/scripts.js
build/community/index.html
build/creation/index.html
build/digitalTwinIot/index.html
build/ecommerce/index.html
build/featureDemos/index.html
build/games/index.html
build/index.html
build/industries/index.html
build/learn/index.html
build/metaverse/index.html
build/native/index.html
build/partners/index.html
build/pressRelease/index.html
build/reactnative/index.html
build/specifications/index.html
build/testimonials/index.html
build/tools/index.html
build/viewer.html
build/viewer/index.html
src/assets/js/scripts.js
src/content/viewer/config.json
src/templates/index-template.html

- Update the "hero" model to the updated airplane (same model used by default in the configurator)
- Update all model links to use the Babylon CDN
- Update to use the embedded default environment
I also updated the gist to match the updates on the landing page.

Model and config updates for Viewer landing page

---

src/content/featureDemos/config.json

updates to links for feature demos
